import os
from datetime import datetime

def export_kicad_schematic(circuit_data: dict, output_path: str = None):
    """
    Export circuit data as .kicad_sch file
    """
    try:
        if not circuit_data:
            return "No circuit data provided!"

        components = circuit_data.get("components", [])
        circuit_name = circuit_data.get("circuit_name", "AI_Generated_Circuit")
        connections = circuit_data.get("connections", [])
        voltage = circuit_data.get("voltage", "5V")

        if not components:
            return "No components found!"

        # Set output path
        if output_path is None:
            docs_path = os.path.expanduser("~\\Documents")
            output_path = os.path.join(docs_path, f"{circuit_name.replace(' ', '_')}.kicad_sch")

        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")

        # KiCad schematic header
        schematic = f"""(kicad_sch
  (version 20231120)
  (generator "AI KiCad Plugin")
  (generator_version "1.0")
  (paper "A4")
  (title_block
    (title "{circuit_name}")
    (date "{datetime.now().strftime('%Y-%m-%d')}")
    (rev "1.0")
    (company "AI Generated")
    (comment 1 "Generated by AI KiCad Plugin")
    (comment 2 "Powered by DeepSeek + Local LLM")
  )
  (lib_symbols
"""
        # Add symbol definitions
        symbol_map = {
            "R": """    (symbol "Device:R"
      (pin_numbers (hide yes))
      (pin_names (offset 0))
      (exclude_from_sim no)
      (in_bom yes)
      (on_board yes)
      (property "Reference" "R" (at 1.905 0 0) (effects (font (size 1.27 1.27)) (justify left)))
      (property "Value" "R" (at -1.905 0 0) (effects (font (size 1.27 1.27)) (justify right)))
      (symbol "R_0_1"
        (rectangle (start -1.016 -2.032) (end 1.016 2.032) (stroke (width 0.2032)) (fill (type none)))
      )
      (symbol "R_1_1"
        (pin passive line (at 0 3.81 270) (length 1.778) (name "~" (effects (font (size 1.27 1.27)))) (number "1" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 0 -3.81 90) (length 1.778) (name "~" (effects (font (size 1.27 1.27)))) (number "2" (effects (font (size 1.27 1.27)))))
      )
    )""",
            "C": """    (symbol "Device:C"
      (pin_numbers (hide yes))
      (pin_names (offset 0.254))
      (exclude_from_sim no)
      (in_bom yes)
      (on_board yes)
      (property "Reference" "C" (at 1.905 0 0) (effects (font (size 1.27 1.27)) (justify left)))
      (property "Value" "C" (at -1.905 0 0) (effects (font (size 1.27 1.27)) (justify right)))
      (symbol "C_0_1"
        (polyline (pts (xy -2.032 -0.762) (xy 2.032 -0.762)) (stroke (width 0.508)))
        (polyline (pts (xy -2.032 0.762) (xy 2.032 0.762)) (stroke (width 0.508)))
      )
      (symbol "C_1_1"
        (pin passive line (at 0 3.81 270) (length 3.048) (name "~" (effects (font (size 1.27 1.27)))) (number "1" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 0 -3.81 90) (length 3.048) (name "~" (effects (font (size 1.27 1.27)))) (number "2" (effects (font (size 1.27 1.27)))))
      )
    )""",
            "LED": """    (symbol "Device:LED"
      (pin_numbers (hide yes))
      (pin_names (offset 1.016) (hide yes))
      (exclude_from_sim no)
      (in_bom yes)
      (on_board yes)
      (property "Reference" "D" (at 0 2.54 0) (effects (font (size 1.27 1.27))))
      (property "Value" "LED" (at 0 -2.54 0) (effects (font (size 1.27 1.27))))
      (symbol "LED_0_1"
        (polyline (pts (xy -1.524 -1.27) (xy -1.524 1.27)) (stroke (width 0.2540)))
        (polyline (pts (xy -1.524 0) (xy 1.524 0)) (stroke (width 0.2540)))
        (polyline (pts (xy 1.524 -1.27) (xy -1.524 0) (xy 1.524 1.27) (xy 1.524 -1.27)) (stroke (width 0.2540)))
      )
      (symbol "LED_1_1"
        (pin passive line (at -3.81 0 0) (length 2.286) (name "K" (effects (font (size 1.27 1.27)))) (number "K" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 3.81 0 180) (length 2.286) (name "A" (effects (font (size 1.27 1.27)))) (number "A" (effects (font (size 1.27 1.27)))))
      )
    )""",
        }

        # Add used symbols
        added_symbols = set()
        for comp in components:
            comp_type = comp.get("type", "R").upper()
            if "RESIST" in comp_type or comp_type == "R":
                if "R" not in added_symbols:
                    schematic += symbol_map.get("R", "")
                    added_symbols.add("R")
            elif "CAP" in comp_type or comp_type == "C":
                if "C" not in added_symbols:
                    schematic += symbol_map.get("C", "")
                    added_symbols.add("C")
            elif "LED" in comp_type or comp_type == "D":
                if "LED" not in added_symbols:
                    schematic += symbol_map.get("LED", "")
                    added_symbols.add("LED")

        schematic += "\n  )\n"

        # Add symbols to schematic
        x_pos = 50
        y_pos = 50
        spacing = 25

        for i, comp in enumerate(components):
            ref = comp.get("ref", f"U{i+1}")
            value = comp.get("value", "")
            comp_type = comp.get("type", "R").upper()

            # Determine library symbol
            if "RESIST" in comp_type or comp_type == "R":
                lib_sym = "Device:R"
            elif "CAP" in comp_type or comp_type == "C":
                lib_sym = "Device:C"
            elif "LED" in comp_type:
                lib_sym = "Device:LED"
            else:
                lib_sym = "Device:R"

            x = x_pos + (i * spacing)
            y = y_pos

            schematic += f"""
  (symbol (lib_id "{lib_sym}") (at {x} {y} 0) (unit 1)
    (exclude_from_sim no) (in_bom yes) (on_board yes)
    (property "Reference" "{ref}" (at {x + 2} {y - 2} 0) (effects (font (size 1.27 1.27))))
    (property "Value" "{value}" (at {x - 2} {y + 2} 0) (effects (font (size 1.27 1.27))))
    (instances (project "ai_generated" (path "/{timestamp}" (reference "{ref}") (unit 1))))
  )"""

        # Add power symbols
        schematic += f"""
  (symbol (lib_id "power:VCC") (at 50 30 0) (unit 1)
    (property "Reference" "#PWR01" (at 50 34 0) (effects (font (size 1.27 1.27)) (hide yes)))
    (property "Value" "{voltage}" (at 50 28 0) (effects (font (size 1.27 1.27))))
    (instances (project "ai_generated" (path "/{timestamp}" (reference "#PWR01") (unit 1))))
  )
  (symbol (lib_id "power:GND") (at 50 120 0) (unit 1)
    (property "Reference" "#PWR02" (at 50 124 0) (effects (font (size 1.27 1.27)) (hide yes)))
    (property "Value" "GND" (at 50 122 0) (effects (font (size 1.27 1.27))))
    (instances (project "ai_generated" (path "/{timestamp}" (reference "#PWR02") (unit 1))))
  )"""

        schematic += "\n)"

        # Save file
        with open(output_path, 'w') as f:
            f.write(schematic)

        return f"✅ Schematic exported!\nFile: {output_path}\nComponents: {len(components)}"

    except Exception as e:
        return f"Error exporting schematic: {str(e)}"


def export_schematic_from_prompt(circuit_data: dict, project_path: str = None):
    """
    Main function to export schematic
    """
    try:
        if project_path is None:
            project_path = os.path.expanduser("~\\Documents")

        circuit_name = circuit_data.get("circuit_name", "AI_Circuit")
        output_file = os.path.join(
            project_path,
            f"{circuit_name.replace(' ', '_')}.kicad_sch"
        )

        return export_kicad_schematic(circuit_data, output_file)

    except Exception as e:
        return f"Error: {str(e)}"import os
from datetime import datetime

def export_kicad_schematic(circuit_data: dict, output_path: str = None):
    try:
        if not circuit_data:
            return "No circuit data provided!"

        components = circuit_data.get("components", [])
        circuit_name = circuit_data.get("circuit_name", "AI_Generated_Circuit")
        voltage = circuit_data.get("voltage", "5V")

        if not components:
            return "No components found!"

        if output_path is None:
            docs_path = os.path.expanduser("~\\Documents")
            output_path = os.path.join(
                docs_path,
                f"{circuit_name.replace(' ', '_')}.kicad_sch"
            )

        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")

        # KiCad schematic header
        schematic = f"""(kicad_sch
  (version 20231120)
  (generator "AI KiCad Plugin")
  (generator_version "1.0")
  (paper "A4")
  (title_block
    (title "{circuit_name}")
    (date "{datetime.now().strftime('%Y-%m-%d')}")
    (rev "1.0")
    (company "AI Generated")
    (comment 1 "Generated by AI KiCad Plugin")
    (comment 2 "Powered by DeepSeek + Local LLM")
  )
  (lib_symbols
"""
        # Symbol definitions
        symbol_map = {
            "R": """    (symbol "Device:R"
      (pin_numbers (hide yes))
      (pin_names (offset 0))
      (in_bom yes) (on_board yes)
      (property "Reference" "R" (at 1.905 0 0) (effects (font (size 1.27 1.27)) (justify left)))
      (property "Value" "R" (at -1.905 0 0) (effects (font (size 1.27 1.27)) (justify right)))
      (symbol "R_0_1"
        (rectangle (start -1.016 -2.032) (end 1.016 2.032) (stroke (width 0.2032)) (fill (type none)))
      )
      (symbol "R_1_1"
        (pin passive line (at 0 3.81 270) (length 1.778) (name "~" (effects (font (size 1.27 1.27)))) (number "1" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 0 -3.81 90) (length 1.778) (name "~" (effects (font (size 1.27 1.27)))) (number "2" (effects (font (size 1.27 1.27)))))
      )
    )""",
            "C": """    (symbol "Device:C"
      (pin_numbers (hide yes))
      (pin_names (offset 0.254))
      (in_bom yes) (on_board yes)
      (property "Reference" "C" (at 1.905 0 0) (effects (font (size 1.27 1.27)) (justify left)))
      (property "Value" "C" (at -1.905 0 0) (effects (font (size 1.27 1.27)) (justify right)))
      (symbol "C_0_1"
        (polyline (pts (xy -2.032 -0.762) (xy 2.032 -0.762)) (stroke (width 0.508)))
        (polyline (pts (xy -2.032 0.762) (xy 2.032 0.762)) (stroke (width 0.508)))
      )
      (symbol "C_1_1"
        (pin passive line (at 0 3.81 270) (length 3.048) (name "~" (effects (font (size 1.27 1.27)))) (number "1" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 0 -3.81 90) (length 3.048) (name "~" (effects (font (size 1.27 1.27)))) (number "2" (effects (font (size 1.27 1.27)))))
      )
    )""",
            "LED": """    (symbol "Device:LED"
      (pin_numbers (hide yes))
      (pin_names (offset 1.016) (hide yes))
      (in_bom yes) (on_board yes)
      (property "Reference" "D" (at 0 2.54 0) (effects (font (size 1.27 1.27))))
      (property "Value" "LED" (at 0 -2.54 0) (effects (font (size 1.27 1.27))))
      (symbol "LED_0_1"
        (polyline (pts (xy -1.524 -1.27) (xy -1.524 1.27)) (stroke (width 0.2540)))
        (polyline (pts (xy -1.524 0) (xy 1.524 0)) (stroke (width 0.2540)))
        (polyline (pts (xy 1.524 -1.27) (xy -1.524 0) (xy 1.524 1.27) (xy 1.524 -1.27)) (stroke (width 0.2540)))
      )
      (symbol "LED_1_1"
        (pin passive line (at -3.81 0 0) (length 2.286) (name "K" (effects (font (size 1.27 1.27)))) (number "K" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 3.81 0 180) (length 2.286) (name "A" (effects (font (size 1.27 1.27)))) (number "A" (effects (font (size 1.27 1.27)))))
      )
    )""",
            "D": """    (symbol "Device:D"
      (pin_numbers (hide yes))
      (pin_names (offset 1.016) (hide yes))
      (in_bom yes) (on_board yes)
      (property "Reference" "D" (at 0 2.54 0) (effects (font (size 1.27 1.27))))
      (property "Value" "D" (at 0 -2.54 0) (effects (font (size 1.27 1.27))))
      (symbol "D_0_1"
        (polyline (pts (xy -1.524 -1.27) (xy -1.524 1.27)) (stroke (width 0.2540)))
        (polyline (pts (xy -1.524 0) (xy 1.524 0)) (stroke (width 0.2540)))
        (polyline (pts (xy 1.524 -1.27) (xy -1.524 0) (xy 1.524 1.27) (xy 1.524 -1.27)) (stroke (width 0.2540)))
      )
      (symbol "D_1_1"
        (pin passive line (at -3.81 0 0) (length 2.286) (name "K" (effects (font (size 1.27 1.27)))) (number "K" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 3.81 0 180) (length 2.286) (name "A" (effects (font (size 1.27 1.27)))) (number "A" (effects (font (size 1.27 1.27)))))
      )
    )""",
        }

        # Add used symbols
        added_symbols = set()
        for comp in components:
            comp_type = comp.get("type", "R").upper()
            if "R" in comp_type and "R" not in added_symbols:
                schematic += symbol_map.get("R", "")
                added_symbols.add("R")
            elif ("CAP" in comp_type or comp_type == "C") and "C" not in added_symbols:
                schematic += symbol_map.get("C", "")
                added_symbols.add("C")
            elif "LED" in comp_type and "LED" not in added_symbols:
                schematic += symbol_map.get("LED", "")
                added_symbols.add("LED")
            elif comp_type == "D" and "D" not in added_symbols:
                schematic += symbol_map.get("D", "")
                added_symbols.add("D")

        schematic += "\n  )\n"

        # Place components
        x_pos = 50
        y_pos = 50
        spacing = 25
        component_positions = {}

        for i, comp in enumerate(components):
            ref = comp.get("ref", f"U{i+1}")
            value = comp.get("value", "")
            comp_type = comp.get("type", "R").upper()

            if "R" in comp_type:
                lib_sym = "Device:R"
            elif "CAP" in comp_type or comp_type == "C":
                lib_sym = "Device:C"
            elif "LED" in comp_type:
                lib_sym = "Device:LED"
            elif comp_type == "D":
                lib_sym = "Device:D"
            else:
                lib_sym = "Device:R"

            x = x_pos + (i * spacing)
            y = y_pos
            component_positions[ref] = (x, y)

            schematic += f"""
  (symbol (lib_id "{lib_sym}") (at {x} {y} 0) (unit 1)
    (exclude_from_sim no) (in_bom yes) (on_board yes)
    (property "Reference" "{ref}" (at {x + 2} {y - 2} 0) (effects (font (size 1.27 1.27))))
    (property "Value" "{value}" (at {x - 2} {y + 2} 0) (effects (font (size 1.27 1.27))))
    (instances (project "ai_generated" (path "/{timestamp}" (reference "{ref}") (unit 1))))
  )"""

        # Add VCC power symbol
        schematic += f"""
  (symbol (lib_id "power:VCC") (at 50 30 0) (unit 1)
    (property "Reference" "#PWR01" (at 50 34 0) (effects (font (size 1.27 1.27)) (hide yes)))
    (property "Value" "{voltage}" (at 50 28 0) (effects (font (size 1.27 1.27))))
    (instances (project "ai_generated" (path "/{timestamp}" (reference "#PWR01") (unit 1))))
  )"""

        # Add GND power symbol
        schematic += f"""
  (symbol (lib_id "power:GND") (at 50 120 0) (unit 1)
    (property "Reference" "#PWR02" (at 50 124 0) (effects (font (size 1.27 1.27)) (hide yes)))
    (property "Value" "GND" (at 50 122 0) (effects (font (size 1.27 1.27))))
    (instances (project "ai_generated" (path "/{timestamp}" (reference "#PWR02") (unit 1))))
  )"""

        # Add wires connecting components in series
        wire_section = "\n"
        if len(components) > 1:
            for i in range(len(components) - 1):
                ref1 = components[i].get("ref", "")
                ref2 = components[i + 1].get("ref", "")
                if ref1 in component_positions and ref2 in component_positions:
                    x1, y1 = component_positions[ref1]
                    x2, y2 = component_positions[ref2]
                    # Wire from pin 2 of comp1 to pin 1 of comp2
                    wire_section += f"""
  (wire (pts (xy {x1} {y1 + 3.81}) (xy {x2} {y2 - 3.81}))
    (stroke (width 0) (type default))
  )"""

        # Wire from VCC to first component
        if components and components[0].get("ref") in component_positions:
            x1, y1 = component_positions[components[0].get("ref")]
            wire_section += f"""
  (wire (pts (xy 50 30) (xy {x1} {y1 - 3.81}))
    (stroke (width 0) (type default))
  )"""

        # Wire from last component to GND
        if components and components[-1].get("ref") in component_positions:
            x1, y1 = component_positions[components[-1].get("ref")]
            wire_section += f"""
  (wire (pts (xy {x1} {y1 + 3.81}) (xy 50 120))
    (stroke (width 0) (type default))
  )"""

        # Add net labels
        net_section = ""
        net_section += f"""
  (net_label (text "VCC") (at 50 30 0)
    (effects (font (size 1.27 1.27)))
  )
  (net_label (text "GND") (at 50 120 0)
    (effects (font (size 1.27 1.27)))
  )"""

        schematic += wire_section
        schematic += net_section
        schematic += "\n)"

        # Save file
        with open(output_path, 'w') as f:
            f.write(schematic)

        return f"Schematic exported!\nFile: {output_path}\nComponents: {len(components)}\nWires: {len(components)} connections added!"

    except Exception as e:
        return f"Error exporting schematic: {str(e)}"


def export_schematic_from_prompt(circuit_data: dict, project_path: str = None):
    try:
        if project_path is None:
            project_path = os.path.expanduser("~\\Documents")

        circuit_name = circuit_data.get("circuit_name", "AI_Circuit")
        output_file = os.path.join(
            project_path,
            f"{circuit_name.replace(' ', '_')}.kicad_sch"
        )

        return export_kicad_schematic(circuit_data, output_file)

    except Exception as e:
        return f"Error: {str(e)}"